### ISSUE TITLE
Compilation failes

### ISSUE THREAD

**Issue by mkrusemark** [tsloughter/rebar3_cuttlefish#30]
I added the plugin with {project_plugins, [rebar3_cuttlefish]}. Download of 0.16.0 succeeds as well as it's dependencies. But compilation files in rebar3 version 3.4.7:

Error: {badmatch,[]}
[{rebar_app_discover,create_app_info,3,
                     [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                      {line,324}]},
 {rebar_app_discover,try_handle_app_src_file,5,
                     [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                      {line,409}]},
 {rebar_utils,filtermap,2,
              [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_utils.erl"},
               {line,109}]},
 {rebar_utils,filtermap,2,
              [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_utils.erl"},
               {line,113}]},
 {rebar_app_discover,do,2,
                     [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                      {line,27}]},
 {rebar_prv_app_discovery,do,1,
                          [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_app_discovery.erl"},
                           {line,38}]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,154}]},
 {rebar3,main,1,
         [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
          {line,66}]}]

Great that you own both projects :-)

Best regards,
Michael

**Comment by mkrusemark** [comment]
Hope this output helps:

$ rebar3 release
===> Fetching rebar3_cuttlefish ({pkg,<<"rebar3_cuttlefish">>,
                                         <<"0.16.0">>})
===> Downloaded package, caching at c:/cygwin/home/mkrusem/.cache/rebar3/hex/default/packages/rebar3_cuttlefish-0.16.0.tar
===> Fetching cuttlefish ({pkg,<<"cuttlefish">>,<<"2.0.12">>})
===> Downloaded package, caching at c:/cygwin/home/mkrusem/.cache/rebar3/hex/default/packages/cuttlefish-2.0.12.tar
===> Fetching getopt ({pkg,<<"getopt">>,<<"0.8.2">>})
===> Downloaded package, caching at c:/cygwin/home/mkrusem/.cache/rebar3/hex/default/packages/getopt-0.8.2.tar
===> Fetching lager ({pkg,<<"lager">>,<<"3.2.4">>})
===> Downloaded package, caching at c:/cygwin/home/mkrusem/.cache/rebar3/hex/default/packages/lager-3.2.4.tar
===> Fetching goldrush ({pkg,<<"goldrush">>,<<"0.1.9">>})
===> Downloaded package, caching at c:/cygwin/home/mkrusem/.cache/rebar3/hex/default/packages/goldrush-0.1.9.tar
===> Compiling goldrush
===> Compiling lager
===> Compiling getopt
===> Compiling cuttlefish
===> Building escript...
===> Compiling rebar3_cuttlefish
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump

Best regards,
Michael

**Comment by mkrusemark** [comment]
I don't expect rebar3 r cuttlefish must deal with filesystem errors. Sorry for this disturbance.

Best regards,
Michael

**Comment by tsloughter** [comment]
No worries :)
