### ISSUE TITLE
Prevent rebar3_cuttlefish from generating a start script

### ISSUE THREAD

**Issue by larshesel** [tsloughter/rebar3_cuttlefish#33]
Hi

We have an issue (which I think might be due to `rebar3_cuttlefish`) which prevents us from moving VerneMQ to OTP21 (https://github.com/erlio/vernemq/issues/738). 

We specify our own start script in the relx overlay (https://github.com/erlio/vernemq/blob/master/rebar.config#L98-L99), but since `rebar3` 3.4.2 the release we get uses the start script from `rebar3_cuttlefish`. 

Is this a bug introduced in `rebar3` 3.4.2 or is it a bug that `rebar3_cuttlefish` doesn't respect the `{generate_start_script, false}`?

I suppose it would be relatively easy to make `rebar3_cuttlefish` skip using it's own start script if that's the case, but wanted to know before making a PR.

**Comment by larshesel** [comment]
I created a 'fix' to work around this in my own branch of rebar3_cuttlefish where I add the overlays from rebar3_cuttlefish first so they can be overwritten by whatever is in the overlays from rebar.config. I think that should probably be the default anyway.

**Comment by larshesel** [comment]
ping @tsloughter

**Comment by tsloughter** [comment]
Is your PR a fix for this?

**Comment by larshesel** [comment]
No, the PR #29 was for OTP 20 :) I'll be happy to rebase that one again if you'd consider merging it.

The fix I did was this: https://github.com/vernemq/rebar3_cuttlefish/commit/97f69b20bf82d0bb99a3cef5d6a6c4578ae95818

I'd also be very happy to make a PR with this if you agree this is the right fix.

**Comment by tsloughter** [comment]
Yea, I think it likely is the right fix. I haven't used cuttlefish in so long, which is why this plugin has stalled. Would you, or maybe you know someone who would, want to take it over? I can transfer the repo.

**Comment by larshesel** [comment]
I just discussed it with the team and we'd be happy to take it over - we'd have to move our existing repo out of the way first, though.

One way to make this transition work could be if we first get our branch with the two fixes merged into master (just created  https://github.com/tsloughter/rebar3_cuttlefish/pull/34 for that), then we could change vernemq to point to tsloughter/rebar3_cuttlefish master, remove our copy, and then we can transfer the repo. Would that work?

**Comment by tsloughter** [comment]
@larshesel I added you as a collaborator. Not sure what all rights that gives you, I may still have to do the actual moving of the repo to your org. But should be able to merge stuff and maybe move it.

**Comment by larshesel** [comment]
Ok, thanks - I'll give it a go!
